### PR TITLE
Update version.hpp

### LINKED ISSUE #1426: sycl::info::platform::version lacks "0"
**Bug summary**

`platform.get_info<sycl::info::platform::version>()` (and `hipsycl::sycl::detail::version_string`) report version `AdaptiveCpp 24.2.0+abcd` instead of `AdaptiveCpp 24.02.0+abcd`.

**To Reproduce**

```console
$ acpp --acpp-version | grep 'AdaptiveCpp version'
  AdaptiveCpp version: 24.02.0+git.0359cac9.20240401.branch.develop.dirty

$ cat test.cpp 
#include <iostream>
#include <sycl/sycl.hpp>

int main()
{
    std::cout << hipsycl::sycl::detail::version_string() << std::endl;
    sycl::platform p;
    std::cout << p.get_info<sycl::info::platform::version>() << std::endl;
}

$ acpp -O2 test.cpp && ./a.out
AdaptiveCpp 24.2.0+git.0359cac9.20240401.branch.develop.dirty
AdaptiveCpp 24.2.0+git.0359cac9.20240401.branch.develop.dirty
```

**Expected behavior**

`AdaptiveCpp 24.02.0+git.0359cac9.20240401.branch.develop.dirty` is returned in both cases.

**Describe your setup**
* ACpp 0359cac9e08d44c48c586ef3ec88e95ac64a4d44
* Describe the dependencies that AdaptiveCpp sits on top of in your setup: 
   * Clang 17.0.6

**Additional context**

Nothing major or critical, just slightly annoying to have a discrepancy in reported versions.

### PR DESCRIPTION
**Pull request by Arpan3323**
The proposed change fixes #1426 

Please let me know if you have any questions or suggestions.

### CODE REVIEW

**Review by fodinabor — COMMENTED** [review]
Hi,
thank you for your contribution!

For the version `24.06` this would do the trick.
However, for the `24.10` version, this will yield `24.010` which is also not what we want...

So three options:
- can we just use the macro stringify thingy as done in the plugin: https://github.com/AdaptiveCpp/AdaptiveCpp/blob/c0add99698c0b5ed8b2865392d22995b1298f98b/src/compiler/AdaptiveCppClangPlugin.cpp#L117 ?
- use `std::stringstream` with the digit modifier
- `ACPP_VERSION_MINOR < 10 ? "0" : ""`

Thanks :)

**Comment by Arpan3323** [comment]
Thanks for letting me know and providing the examples :). I have updated my changes accordingly. Please feel free to let me know if there is anything else I may have missed

**Review by fodinabor — APPROVED** [review]
Should be good, I think.
Thanks!

**Review by illuhad — APPROVED** [review]
Thanks!

**Pull request merged**
