### PR TITLE
fix HIPSYCL_LIBKERNEL_COMPILER_SUPPORTS_{CUDA,HIP} variables

### PR DESCRIPTION
**Pull request by garymm**
They were being set to 0 or 1 but being checked to see if they
were defined. Instead just define them rather than setting them to 1
and do not do anything rather than set them to 0.

### CODE REVIEW

**Comment by illuhad** [comment]
Thanks. We are using the pattern of being set to 0 or 1 massively also for all other-backend queries such as `HIPSYCL_LIBKERNEL_IS_DEVICE_PASS_CUDA/HIP/...`. I wonder if it might be better to just align the use of these variables with them being consistently set to 0 or 1, as with the other variables?

**Comment by garymm** [comment]
@illuhad please just tell me what you want, or feel free to make the change yourself, should be as simple as modifying this to check for 1 rather than defined:

https://github.com/OpenSYCL/OpenSYCL/blob/27542ab71a72a0dfefdca58c2b0a42462a9c5300/include/hipSYCL/sycl/backend.hpp#L51

**Comment by garymm** [comment]
Still valid but closing since it's been ignored for so long.

**Comment by illuhad** [comment]
Apologies, nobody has the intent to ignore things, but sometimes other things can come in between and then things can be forgotten :(

If you still want this in, I'd prefer modifying the checks, not the definition of these macros.

**Comment by garymm** [comment]
I'm not using this library at the moment, but it seems like a bug you might want to fix.

**Pull request closed without merging**
