### PR TITLE
Added support for boost installations other than the default location

### PR DESCRIPTION
**Pull request by sbalint98**
This PR should allow the user to use boost installations that are in a custom location easily.

### CODE REVIEW

**Comment by illuhad** [comment]
Wouldn't it be better to add generalized `cxx_flags` and `link_line` arguments for the CPU backend? Otherwise we have the same issue for OpenMP, or other dependencies.

**Comment by sbalint98** [comment]
Well, boost is a dependency of both the `omp` and the `omp_sequential` backend, if I understood correctly. And since the sequential backend is temporary it might be unnecessary to expose its dependencies.  And by the same token, would you also remove the `default-cuda-path` and the `default-rocm-path` vars?

**Comment by illuhad** [comment]
boost as a hard dependency is probably going to remain even after `omp_sequential` is removed since we need `boost.fiber` for replacement backends e.g. based on TBB as well.

I don't think we can remove existing arguments such the cuda path or rocm path, but we might want to change how they work internally: I would like to have them set corresponding substitution variables which then are used by default cxx flags and link lines.

**Comment by sbalint98** [comment]
> boost as a hard dependency is probably going to remain even after omp_sequential is removed since we need boost.fiber for replacement backends e.g. based on TBB as well.

I wanted to open a separate PR with the exposure of the cxx flags and the link lines for all backends, but probably it might be better to just close this PR and move these changes in the other one. 

> I don't think we can remove existing arguments such the cuda path or rocm path, but we might want to change how they work internally: I would like to have them set corresponding substitution variables which then are used by default cxx flags and link lines.

I am not sure if I fully understand this. In syclcc the `default-cuda/rocm-path` specified in syclcc.json are currently used to set substitutions variables for the `HIPSYCL_CUDA/ROCM_PATH` `HIPSYCL_CUDA/ROCM_LIB_PATH` vars that are substituted from the cxx and link lines for cuda and rocm. How would you like to change this behaviour?

**Comment by illuhad** [comment]
> I wanted to open a separate PR with the exposure of the cxx flags and the link lines for all backends, but probably it might be better to just close this PR and move these changes in the other one.

okay :)

>  I am not sure if I fully understand this. In syclcc the default-cuda/rocm-path specified in syclcc.json are currently used to set substitutions variables for the HIPSYCL_CUDA/ROCM_PATH HIPSYCL_CUDA/ROCM_LIB_PATH vars that are substituted from the cxx and link lines for cuda and rocm. How would you like to change this behaviour?

Only in a subtle way. I think the idea would be to not refer to them directly, but only potentially when the cxx line or link line is evaluated and their substitution variables are referenced there. I think there are still a couple of places that use them directly inside `syclcc`.

**Pull request closed without merging**
