### PR TITLE
WIP: Add initial Intel GPU support / Level Zero runtime backend / SPIR-V compilation

### PR DESCRIPTION
**Pull request by illuhad**
This adds initial support for Intel GPUs using a Level Zero runtime backend and SPIR-V. This is **highly experimental and WIP**. The basics work, but there are many features that are not yet implemented, including:
* local memory
* reductions
* group algorithms
* multi-dimensional data transfers
* probably other things

Nevertheless, I would like to merge the initial support soon to avoid the PR getting too large.

SPIR-V compilation is carried out using the clang SYCL frontend. This means that this requires a clang that has Intel's patches merged such as DPC++/[Intel's LLVM fork](https://github.com/intel/llvm).

It might seem a bit odd at first glance to implement SYCL using components from another SYCL implementation, but it makes perfect sense given that:
* hipSYCL is designed to **aggregate multiple toolchains** under a single roof and a single SYCL interface. Integrating with the clang SYCL frontend is no different to what we already do with CUDA and HIP, except that we don't need clang plugins to make clang's SYCL frontend understand SYCL.
* Intel is actively upstreaming their bits for SYCL support in clang. As such, the clang SYCL toolchain will be ubiquitous in the future, just like the clang CUDA and HIP toolchains. This PR therefore allows hipSYCL to **unite the most important clang toolchains**.
* Because hipSYCL can compile with multiple toolchains/clang drivers simultaneously, it means **users are now able to compile to a binary that contains compiled native kernels for OpenMP, CUDA, HIP and SPIR-V.**

As a result, this PR allows hipSYCL to compile to a **binary that runs on CPUs, AMD GPUs, NVIDIA GPUs, and Intel GPUs**.

Effectively this PR positions hipSYCL as an alternative framework for the clang SYCL frontend to run in, by using the combination:
* hipSYCL compiler driver syclcc +
* hipSYCL headers +
* hipSYCL runtime +
* hipSYCL mechanism for embedding compiled kernels/creating "fat binaries" +
* clang SYCL frontend/SPIR-V code generation

Compilation for SPIR-V can be enabled by passing `spirv` to hipSYCL targets, e.g.: 
```
syclcc --hipsycl-targets="omp;spirv;cuda:sm_70"
```
to compile for OpenMP, SPIR-V and CUDA.

### CODE REVIEW

**Comment by illuhad** [comment]
Did some work to get the unit tests to compile with the Level Zero/SPIR-V backend - I got until `tests/math.cpp`, when I hit the following ICE:
```
LLVM ERROR: Size of the memcpy should match the allocated memory
PLEASE submit a bug report to https://software.intel.com/en-us/support/priority-support and include the crash backtrace.
Stack dump:
0.      Program arguments: /opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv -o /tmp/hipSYCL-syclcc-_q35icp7/hipsycl-kernels.spv -spirv-max-version=1.1 -spirv-ext=+all,-SPV_INTEL_usm_storage_classes /tmp/math-c16338.bc 
1.      Running pass 'Lower llvm.memmove into llvm.memcpy' on module '/tmp/math-c16338.bc'.
 #0 0x000055e86bd19e37 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x237e37)
 #1 0x000055e86bd18680 llvm::sys::RunSignalHandlers() (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x236680)
 #2 0x000055e86bd1a0f1 SignalHandler(int) (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x2380f1)
 #3 0x00007f22080603c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007f2207e9f18b raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f2207e7e859 abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81:7
 #6 0x000055e86bcffdea (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x21ddea)
 #7 0x000055e86bcffc47 (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x21dc47)
 #8 0x000055e86bfe3d1c (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x501d1c)
 #9 0x000055e86bfe34a9 SPIRV::SPIRVLowerMemmove::runOnModule(llvm::Module&) (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x5014a9)
#10 0x000055e86c09a848 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x5b8848)
#11 0x000055e86bf3310e llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x45110e)
#12 0x000055e86bec5898 main (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x3e3898)
#13 0x00007f2207e800b3 __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342:3
#14 0x000055e86bec0393 _start (/opt/intel/oneapi/compiler/latest/linux/bin/llvm-spirv+0x3de393)
clang++: error: unable to execute command: Aborted (core dumped)
clang++: error: llvm-spirv command failed due to signal (use -v to see invocation)
Intel(R) oneAPI DPC++ Compiler 2021.1.2 (2020.10.0.1214)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/latest/linux/bin
clang++: note: diagnostic msg: 
********************
```

Seems to be a known issue: https://github.com/intel/llvm/issues/2376

**Comment by illuhad** [comment]
@hipSYCL-ci-bot test again

**Comment by fodinabor** [comment]
Although the error message is different.. in your case it's complaining about `Size of the memcpy should match the allocated memory`, while the assertion in the linked bug is `llvm.memmove of non-constant length not supported`, so might actually be something to debug..? :$

**Comment by illuhad** [comment]
@fodinabor True.. It's probably still related in some way. In the end we're just using vanilla clang SYCL/DPC++ with our own headers.

**Comment by illuhad** [comment]
Let's prepare merging to simplify maintenance. This PR has pretty much zero impact on existing backends, so should not hurt to merge.

@hipSYCL-ci-bot test please

**Pull request merged**
