### PR TITLE
NFC: Remove trailing whitespace

### PR DESCRIPTION
**Pull request by hdelan**
Non functional change. Removing trailing whitespace.

### CODE REVIEW

**Comment by illuhad** [comment]
Wow, thank you! This PR touches pretty much every file. Would it be possible to split it up into smaller PRs for the different components of the project? Otherwise handling all the merge conflicts might be difficult.

**Comment by hdelan** [comment]
Yep sure no problem. Let me know how I should split this up into smaller PRs

**Comment by illuhad** [comment]
Perhaps one simple heuristic might be by subdirectory? Given that all of this is NFC, we can group the changes arbitrarily, so I don't have a strong opinion.

**Comment by hdelan** [comment]
OK sure so is it enough to subdivide into `include`, `src` and `test`?

**Pull request closed without merging**
