### PR TITLE
[stdpar][algorithms] Add support for scan-based algorithms

### PR DESCRIPTION
**Pull request by illuhad**
* Implements `std::in/exclusive_scan`
* Implements `std::transform_in/exclusive_scan`
* Fixes previously incorrect behavior of `copy_if`, which did not perform a scan therefore did not behave correctly.
* Exposed both on the stdpar layer as well algorithms library
* Supports arbitrary data types (even if they are not default constructible). However, these cases may result in lower performance since a fallback code path is used.
* Dedicated code path for CPU backend for more performance on CPU
* Supported both with SSCP and SMCP compilation flows
* Fixes certain issues around atomics which were encountered, since the scan requires acquire/release atomic semantics.

The implemented scan is a decoupled lookback scan, so *not* a naive algorithm. However, performance is currently only at ~50% of peak memory bandwidth (e.g., babelstream measures 800 GB/s copy, then you can scan with ~400GB/s).
From my testing, it seems that our scan is currently limited by the performance of the work group scan. Currently, the implemented work group scan is rather simplistic, and is actually only intended as a fallback - once the SSCP group algorithm implementations PR is available, we can replace the fallback work group scan with the scan from the SYCL 2020 group algorithms for the cases supported by the group algorithms API. I expect that this will be substantially faster since it will actually use subgroup operations, which our fallback does not use.

Further speedup could be attained by implementing the memory stride on a subgroup level and not on the work group level. However, this generates complexities on some backends (SPIR-V...) where the subgroup size is not a constant, not necessarily uniform, and not as easily known. So I would only do this optimization if it turns out that the SYCL group algorithms cannot deliver the speedup that I'm hoping for.

The scan requires hardware that supports acquire/release semantics and certain scheduling properties (in particular, that work groups are guaranteed to finish once they have started executing).
This is not a problem on NVIDIA GPU, AMD GPU, Intel GPU and CPU, but in theory it could happen that e.g. some OpenCL devices don't support this, as it's not guaranteed behavior by OpenCL. I think this is something we can worry about if somebody actually discovers such a device :-)
In practice the required guarantees are met by all devices that AdaptiveCpp is primarily targeting.

Draft because I'd like to wait until the SSCP group algorithm implementations are available for further experimentation.

### CODE REVIEW

**Comment by al42and** [comment]
Are there any known issues with RDNA? I'm getting `compile(): jit::compile: Encountered errors: 0: LLVMToAmdgpu: hiprtcLinkComplete() failed.` with a simple program trying to use it the algorithm:

<details>
<summary>Source</summary>

```cpp
#include <hipSYCL/algorithms/numeric.hpp>
#include <sycl/sycl.hpp>

int main() {
  for (const auto &device : sycl::device::get_devices()) {
    // Creating SYCL queue
    sycl::queue q(device, {sycl::property::queue::in_order()});

    std::cout << "Running on " << device.get_info<sycl::info::device::name>()
              << "\n";

    constexpr size_t size = 8192;
    constexpr int wgSize = 256;
    int *dataD = sycl::malloc_device<int>(size, q);
    std::vector<int> dataH(size);

    std::cout << "Running an algorithm..." << std::endl;
    {
      namespace hau = hipsycl::algorithms::util;
      hau::allocation_cache device_scratch_cache{hau::allocation_type::device};
      hau::allocation_group scratch{&device_scratch_cache,
                                    device.AdaptiveCpp_device_id()};
      q.fill<int>(dataD, 1, size);
      hipsycl::algorithms::exclusive_scan(q, scratch, dataD, dataD + size,
                                          dataD, 0, sycl::plus<int>{});
      q.copy<int>(dataD, dataH.data(), size).wait();

      int numFail = 0;
      for (size_t i = 0; i < size; i++) {
        numFail += (dataH[i] != i);
      }
      std::cout << "Got " << numFail << " failues!" << std::endl;
    }
  }
  return 0;
}
```

</details>

<details>
<summary>Log</summary>

```console
$ acpp -g -O2 --acpp-targets='generic' 1628.cpp && ./a.out 
Running on NVIDIA GeForce RTX 3060
Running an algorithm...
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
[AdaptiveCpp Warning] kernel_cache: This application run has resulted in new binaries being JIT-compiled. This indicates that the runtime optimization process has not yet reached peak performance. You may want to run the application again until this warning no longer appears to achieve optimal performance.
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
Got 0 failues!
Running on AdaptiveCpp OpenMP host device
Running an algorithm...
Got 0 failues!
Running on Intel(R) Arc(TM) A770 Graphics
Running an algorithm...
Got 0 failues!
Running on Intel(R) UHD Graphics 770
Running an algorithm...
Got 0 failues!
Running on AMD Radeon RX 6400
Running an algorithm...
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:310 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.

[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:696 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:310 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.

[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:696 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:310 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.

[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:696 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
Got 8192 failues!
============== hipSYCL error report ============== 
hipSYCL has caught the following unhandled asynchronous errors: 

   0. from /home/aland/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:310 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.

   1. from /home/aland/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:696 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
   2. from /home/aland/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:310 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.

   3. from /home/aland/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:696 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
   4. from /home/aland/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:310 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.

   5. from /home/aland/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:696 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
The application will now be terminated.
terminate called without an active exception
Aborted (core dumped)

$ ACPP_VISIBILITY_MASK=hip AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 ~/sycl_tests/a.out &> hipjit.log
```

[hipjit.log](https://github.com/user-attachments/files/18024719/hipjit.log)

</details>

<details>
<summary>ACpp version</summary>

```console
$ acpp --acpp-version
acpp [AdaptiveCpp compilation driver], Copyright (C) 2018-2024 Aksel Alpay and the AdaptiveCpp project
  AdaptiveCpp version: 24.06.0+git.e55293ae.20241202.branch.develop.dirty
  Installation root: /home/aland/local
  Plugin LLVM version: 18, can accelerate CPU: True
  Available runtime backends:
     librt-backend-cuda.so
     librt-backend-omp.so
     librt-backend-ze.so
     librt-backend-hip.so
     librt-backend-ocl.so


Full configuration [can be overridden using environment variables or command line arguments]:
    version-major: 24
    version-minor: 06
    version-patch: 0
    version-suffix: +git.e55293ae.20241202.branch.develop.dirty
    plugin-llvm-version-major: 18
    plugin-with-cpu-acceleration: true
    default-clang: /usr/lib/llvm-18/bin/clang++
    default-targets: generic
    default-cpu-cxx: /usr/bin/clang++-18
    default-rocm-path: /opt/rocm
    default-use-bootstrap-mode: false
    default-is-dryrun: false
    default-use-accelerated-cpu: true
    default-clang-include-path: /usr/lib/llvm-18/lib/clang/18/include/..
    default-sequential-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
    default-sequential-cxx-flags: -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-omp-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
    default-omp-cxx-flags: -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-is-explicit-multipass: false
    default-save-temps: false
    default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
    default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike -isystem /usr/lib/llvm-18/lib/clang/18/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
    default-nvcxx: (unconfigured)
    default-cuda-path: /usr/local/cuda
    default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
    default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike
```

</details>

**Comment by illuhad** [comment]
@al42and hm, interesting. I would expect it to work on RDNA as well, but I don't have an RDNA GPU for testing. The only somewhat uncommon thing it uses is acquire/release atomic loads and stores. Perhaps there is an LLVM bug lowering these atomics, or perhaps there is an unrelated issue that just happens to manifest here. Can you set the environment variables that are mentioned in the log? This way we can hopefully get some more information about what the problem is.

**Comment by illuhad** [comment]
Never mind, I missed that you had already attached the JIT log. It seems to choke on some dwarf symbols. Does it work without `-g`?

**Comment by al42and** [comment]
> Never mind, I missed that you had already attached the JIT log. It seems to choke on some dwarf symbols. Does it work without -g?

Good point.

Yes, now it works (except with OpenCL backend for the internal GPU, for some reason; but it is likely unrelated):

```
$ acpp -O2 --acpp-targets='generic' 1628.cpp && ./a.out 
Running on NVIDIA GeForce RTX 3060
Running an algorithm...
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
[AdaptiveCpp Warning] kernel_cache: This application run has resulted in new binaries being JIT-compiled. This indicates that the runtime optimization process has not yet reached peak performance. You may want to run the application again until this warning no longer appears to achieve optimal performance.
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
'+ptx86' is not a recognized feature for this target (ignoring feature)
Got 0 failues!
Running on AdaptiveCpp OpenMP host device
Running an algorithm...
Got 0 failues!
Running on Intel(R) Arc(TM) A770 Graphics
Running an algorithm...
Got 0 failues!
Running on Intel(R) UHD Graphics 770
Running an algorithm...
Got 0 failues!
Running on AMD Radeon RX 6400
Running an algorithm...
Got 0 failues!
Running on Intel(R) Arc(TM) A770 Graphics
Running an algorithm...
Got 0 failues!
Running on Intel(R) UHD Graphics 770
Running an algorithm...
Segmentation fault (core dumped)

Thread 9 "a.out" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffbd400640 (LWP 1168503)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140736368477760) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736368477760) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736368477760) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736368477760, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7ca2b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7cae20c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7cae277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7cae4d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7ca27ac in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7f90718 in hipsycl::rt::(anonymous namespace)::determine_target_lane(std::shared_ptr<hipsycl::rt::dag_node> const&, sbo::small_vector<std::shared_ptr<hipsycl::rt::dag_node>, 8ul> const&, hipsycl::rt::multi_queue_executor const*, hipsycl::rt::moving_statistics const&, hipsycl::rt::backend_execution_lane_range) () from /home/aland/local/lib/libacpp-rt.so
#11 0x00007ffff7f901e6 in hipsycl::rt::multi_queue_executor::submit_directly(std::shared_ptr<hipsycl::rt::dag_node> const&, hipsycl::rt::operation*, sbo::small_vector<std::shared_ptr<hipsycl::rt::dag_node>, 8ul> const&) () from /home/aland/local/lib/libacpp-rt.so
#12 0x00007ffff7f9c0cb in hipsycl::rt::(anonymous namespace)::submit(hipsycl::rt::backend_executor*, std::shared_ptr<hipsycl::rt::dag_node>, hipsycl::rt::operation*) () from /home/aland/local/lib/libacpp-rt.so
#13 0x00007ffff7f97f13 in hipsycl::rt::dag_direct_scheduler::submit(std::shared_ptr<hipsycl::rt::dag_node>) () from /home/aland/local/lib/libacpp-rt.so
#14 0x00007ffff7f9e128 in hipsycl::rt::dag_unbound_scheduler::submit(std::shared_ptr<hipsycl::rt::dag_node>) () from /home/aland/local/lib/libacpp-rt.so
#15 0x00007ffff7f9ffd6 in std::_Function_handler<void (), hipsycl::rt::dag_manager::flush_async()::$_0>::_M_invoke(std::_Any_data const&) () from /home/aland/local/lib/libacpp-rt.so
#16 0x00007ffff7fa8585 in hipsycl::rt::worker_thread::work() () from /home/aland/local/lib/libacpp-rt.so
#17 0x00007ffff7cdc253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007ffff7894ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#19 0x00007ffff7926850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

(also, I have failed to correctly type "failures" :facepalm:)

**Comment by illuhad** [comment]
> Yes, now it works

Great. ptxas also chokes on some of the debug symbols that clang generates, so we already strip debug symbols from IR when compiling for CUDA. We could do the same on AMD, but I'd prefer not to do this, unless absolutely necessary.
I'm curious about your combination of AdaptiveCpp LLVM and ROCm LLVM. Which exact versions are you using?

> (except with OpenCL backend for the internal GPU, for some reason; but it is likely unrelated

hm, yeah that looks unrelated. We have an iGPU in CI where this PR works too. I don't know however what could cause that issue either. What's a bit strange is that it goes down the `multi_queue_executor` path when you are in fact using an in-order queue, so it should never invoke that code.

**Comment by al42and** [comment]
> I'm curious about your combination of AdaptiveCpp LLVM and ROCm LLVM. Which exact versions are you using?

Mainline Clang 18.1 (from LLVM APT repos) + ROCm 6.1.1

**Comment by illuhad** [comment]
> Mainline Clang 18.1 (from LLVM APT repos) + ROCm 6.1.1

ROCm 6.1 is based on LLVM 17. So your configuration does not conform with the SSCP requirement that AdaptiveCpp LLVM <= ROCm LLVM: https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/installing.md#compilation-flows

This is needed because AdaptiveCpp needs to hand IR over to ROCm, but LLVM IR only makes forward compatibility guarantees, not backwards compatibility. So newer LLVM versions can ingest IR from older versions, but not vice versa.

In your case, presumably something was changed in LLVM between 17 and 18 as to how debug symbols are handled, so ROCm LLVM 17 cannot handle the debug symbols from LLVM 18.

These IR compatibility issues tend to be spurious and hard to predict, so it is entirely possible that things appear to be working unless *something* is used that happens to hit one of the things that was changed between LLVM versions.

**Comment by al42and** [comment]
> ROCm 6.1 is based on LLVM 17. So your configuration does not conform with the SSCP requirement that AdaptiveCpp LLVM <= ROCm LLVM: [develop/doc/installing.md#compilation-flows](https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/installing.md#compilation-flows)

Ah, good catch again. I though it was 18.

> These IR compatibility issues tend to be spurious and hard to predict, so it is entirely possible that things appear to be working unless something is used that happens to hit one of the things that was changed between LLVM versions.

Yeah, a simple example worked, so I did not check the versions further.

**Comment by illuhad** [comment]
Ok, let's get it in now so that we can do more integration testing and have other algorithm-related PRs on top of it. We can always add the performance optimizations later.

**Pull request merged**
