### PR TITLE
Fix deprecation warnings when using LLVM 18 & 19

### PR DESCRIPTION
**Pull request by nilsfriess**
In newest LLVM two functions in the StringRef class were deprecated. This PR adds a simple function to use the new one if compiling with LLVM >= 18.

### CODE REVIEW

**Comment by fodinabor** [comment]
while at it.. since LLVM 19 just branched (and you fixed one of the blocking issues already - the starts_with func), can you add that to CI and check if there's more issues?

**Comment by al42and** [comment]
I happened to have that lying around: https://github.com/AdaptiveCpp/AdaptiveCpp/commit/8e13b26d92e2e33d18c0fa61a1b3eb86ba239c86

There's been some pruning of headers, so we cannot rely on transitive includes much more; `equals` method has been deprecated on some object, and, annoyingly, DiagnosticHandler::DiagnosticHandlerTy changed its first argument type from reference to a pointer.

**Comment by illuhad** [comment]
You will probably also need this PR: https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1551

**Comment by nilsfriess** [comment]
Should we add LLVM 19 already to CI?

**Comment by illuhad** [comment]
> Should we add LLVM 19 already to CI?

If it works, why not :)

**Review by illuhad — APPROVED** [review]

**Pull request merged**
